### PR TITLE
Remove double substitution from liveness/readiness probes.

### PR DESCRIPTION
**Pull request by awood**
Double substitution works in zsh but not in bash!

### CODE REVIEW

**Comment by awood** [comment]
@mstead I can confirm this deploys correctly in the CI now.  There's still the potential for a double slash, but I'm willing to live with that.

**Comment by kahowell** [comment]
> @mstead I can confirm this deploys correctly in the CI now. There's still the potential for a double slash, but I'm willing to live with that.

When the double slash happens, doesn't this break the check though?

**Comment by awood** [comment]
> When the double slash happens, doesn't this break the check though?

I don't think so.  In theory, the URL should still work.  We should check though.

```
% curl -s --fail -o nul https://www.redhat.com/en/about  
% echo $?
0
% curl -s --fail -o nul https://www.redhat.com/en//about 
% echo $?
0
% curl -s --fail -o nul https://www.redhat.com/en/abert  
% echo $?
22
```

**Comment by kahowell** [comment]
@awood 

```
sh-4.2$ /usr/bin/curl -s http://localhost:8080/r/insights/platform/rhsm-conduit/v1/status/ready
{"availability":"OK"}sh-4.2$
sh-4.2$
sh-4.2$ /usr/bin/curl -s http://localhost:8080//r/insights/platform/rhsm-conduit/v1/status/ready
{"errors":[{"status":"404","code":"RHSMCONDUIT1001","title":"An rhsm-conduit API error has occurred.","detail":"RESTEASY003210: Could not find resource for full path: http://localhost:8080//r/insights/platform/rhsm-conduit/v1/status/ready"}]}
```

**Pull request merged**
