### PR TITLE
ENT-1372: Grabbing account number from Pinhead data

### PR DESCRIPTION
**Pull request by sskracic**
WiP to get the early feedback.  I'm about to rip off all locally managed org_id<->acct_number mapping facilities.

### CODE REVIEW

**Comment by barnabycourt** [comment]
@sskracic are you looking for a review from other members of the team of this early branch or is the WiP just for your own tracking purposes?

**Comment by sskracic** [comment]
@barnabycourt I would say it's the latter, although I would like to give the team a heads up on what approach I am taking.  Once I am fully satisfied with the PR (eg. test coverage could be better), I'll remove the 'WiP' from the title and move the card into the 'Waiting for review' column.

**Comment by kahowell** [comment]
@sskracic looks good so far. Once you're happy with it let me know.

**Comment by sskracic** [comment]
This is now ready for review.

**Pull request merged**
